version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env